### PR TITLE
Feat: Add alma and rocky

### PR DESCRIPTION
**Pull request by srbala**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
This PR will add AlmaLinux and RockyLinux into supported OS for security scanning

#### Where should the reviewer start?
Changes follows same pattern as CentOS, changes added all places CentOS is referenced/noted

#### How should this be manually tested?
Follow team/project standards for testing standards

#### Any background context you want to provide?
AlmaLinux `docker pull almalinux:8`
Rocky Linux `docker pull rockerlinux/rockylinux:8`

#### What are the relevant tickets?
Provide command line support to scan AlmaLinux and Rocky Linux OSs https://github.com/snyk/snyk/issues/2071

### CODE REVIEW

**Comment by shaninja** [comment]
Hey @srbala! Thank you so much for your contribution and the effort you put into this PR 🙏  We really appreciate it.

We need to consult with a different team and see if this change would work as-is, or if there are any other changes required.

**Comment by srbala** [comment]
@shaninja any update on your discussion with other team?

**Comment by srbala** [comment]
@shaninja any update on this PR

**Comment by shaninja** [comment]
Hey @srbala,
Unfortunately, we are still not supporting Alma and Rocky’s security advisories, meaning that even if we added support in this PR, we wouldn't have any vulnerability information for these OS.
Our security team is exploring adding the needed data sources, and only after we’ll have the needed data to present vulnerabilities, we can invest in adding these OS for security scanning.

**Comment by agatakrajewska** [comment]
Hi @srbala,
I'm closing this PR as per the latest comment from @shaninja, we do not support security advisories yet for Rocky or Alma.
Our goal is to keep adding advisories, the list of the supported distros is constantly updated and you can find it here: https://docs.snyk.io/products/snyk-container/snyk-container-security-basics/supported-operating-system-distributions. We don't have this particular support in the nearest plans but please feel free to check with us as well! 🙏

**Comment by jaboutboul** [comment]
Hi @agatakrajewska. How do you guys consume advisory info? We have several data sources which can probably help you. Tenable/Nessus, Qualys and Anchore are all consuming from those sources.

**Pull request closed without merging**
