### PR TITLE
chore: fix minor typo

### PR DESCRIPTION
**Pull request by rajivshah3**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
Fixes a typo (`binarisAnalysis` -> `binariesAnalysis`)

#### Where should the reviewer start?
N/A

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant tickets?
N/A

#### Screenshots
N/A

#### Additional questions
N/A

### CODE REVIEW

**Comment by shaimendel** [comment]
Hi dear @rajivshah3! thank you so much for this fix :) 
`fix` commits mean that there is some logic change in the commit so a new release will be created with an advanced minor version. since this commit does not change logic - do you mind changing the commit type (and PR title) to `chore` instead?

**Comment by rajivshah3** [comment]
> do you mind changing the commit type (and PR title) to chore instead?

Done ✅

**Comment by shaimendel** [comment]
I'm about to close and reopen the PR to test a circleci config

**Comment by shaimendel** [comment]
@rajivshah3 thanks a lot for your contribution! hope to hear more from you :)

**Pull request merged**
